import React from 'react'

const DenotifiedTribes = () => {
  return (
    <>
    <p>The colonial history that imposed Criminal Tribes Act (CTA) on about 200 communities in India continues to haunt these communities in current scenario as well. CTA was enacted in 1871 and it bracketed the communities as ‘Born Criminals’. Under this act the communities who used to live a nomadic lifestyle were restricted, monitored and constant surveillance over their movement was imposed. Moreover their traditional means of livelihoods were snatched and the communities were put into detention centers-like settlements where they were economically exploited and restricted from all sorts of movement. This also led to the stigmatization of these communities as ‘born criminals’. All though the independent India scrapped CTA, the stigmatization of their identity as ‘born criminals’ or ‘habitual offenders’ prevails robustly.</p>
    <p>De-notified tribal communities were forced to adapt ‘settled’ way of living, pushed away from forest and resources of forests and poorly rehabilitated. Currently they either reside in their villages and earn through agricultural labor or have settled in bastis of cities with almost no realization of welfare mechanisms that can ensure upward socio-economic mobility. At the same time, they are also kept deprived of their rights and face social exclusion, institutional violence and discrimination in their everyday lives.</p>
    <p>At Muskaan, we have been working with people from DNT communities since last two decades. Initially, when we understood that hardly any child from the community is being able to pursue higher secondary education because of the range of issues that arises from the prevailing stigma and the biases associated with the community. We started our interventions in the bastis of Pardhi community (one of the DNTs). Alongside working on the lines of ensuring that children in Pardhi community can continue their education, we realized that there are several reasons for the very frequent drop-outs of children. The community survives amidst the severe realities at their home (institutional violence, discrimination at school, workplace, lack of livelihood opportunities, etc.) that pushes children to go and collect scrap so that they too can contribute in providing for the family.</p>
    <p>The culmination of these reasons creates an environment of trauma in the ecosystem of the gated bastis of the community. Subsequently the mental health too, takes a toll and the suicidal tendencies are often noticeable. Upon realizing these severities, Muskaan also began developing interventions focusing on these aspects because education in hindsight of these difficult realities limits any holistic socio-economic mobility of the community.</p>
    <p>Since we started our school Jeevan Shiksha Pahal, a basti of Pardhi community where not a single child was able to pursue higher secondary education, has now a group of children who are on the verge of finishing their higher secondary education. This group is now pertinent to follow their dreams. There is a youth group by the name Majal who works around the issues of their community which persists internally (orthodox, patriarchal processes and norms of local tribal councils) as well as issues prevailing because of external agents like institutional biases, social discrimination, etc. Alongside this, interventions around child protection, creating opportunities focusing on alternative pedagogy of learning such as theater, sport (Ultimate Frisbee) music, barefoot basti counselors (that acknowledges the trauma of the people in their basti and supports the individuals), creating income-generating opportunities, etc. are some of the interventions that Muskaan works on alongside the Pardhi community.</p>
    <p>Realizing the presence and the vulnerability of other DNTs that live in and around Bhopal as well as in Madhya Pradesh, we have started engaging with DNT communities like Kanjar, Bachhda, Bediya, Dafale, etc. in limited capacity. We are determined to expand our interventions and engage with vulnerable DNT communities and form a network of youth from these communities that comes together to challenge the biases and the stigma that De-notified tribes are collectively struggling with. The aim is to ensure the identity of belonging to a DNT community avails dignity and not the everyday struggle for their survival.</p>
    </>
  )
}

export default DenotifiedTribes