import React from 'react'

const BuildingPerspectives = () => {
  return (
    <>
      <p>We attempt to inculcate the social and political consciousness among the children through the subject of social study. We try to ensure that the issues, incidences and the struggles that we discuss are also resonating to the lives that children are living alongside being able to understand about the same comprehensively in the larger context. The intent is to ensure that children can critically think about their vicinity and the everyday issues of Dalit, Adivasi, Minority communities and their issues of past and the present, the struggles. Children can thereby understand diverse issues with a critical lens which shall evolve and they can form an opinion about the same and can respond to such issues through thoughts as well as actions.</p>
    <p>To also be able to ensure that children can reflect about the disconnection in the content written in the books and the experiences that they live with. Dignity of an individual, equity in the opportunities, equality, and justice are some of the values that they can assess how far or near (relevant) are these in their lives. So, they can also understand why they and the communities like theirs are deprived of resources and education. The intention to think along on these lines is to ensure that children, instead of blaming themselves, can claim their rights, struggle for the same and prepare themselves as well. The collective effort is to understand and talk about the struggles of our people, know the history which can uplift the confidence of the children and can establish a common respect and pride for their community as they evolve.</p>
    <p>The consistent efforts are also around understanding the prevailing perverse inequality based on sexuality, caste, class, religion based discrimination and the values such as communal harmony can be inculcated.</p>
    <h6>To evolve the mentioned values, our preponderant activities are as follows:</h6>
    <p>We have prepared some learning materials and lesson plan around several issues such as the dominance of corporate loot, displacement of adivasi communities, violence, etc. that is frequently discussed with children. We read these material with children, discuss about it, try to understand the cause of these issues and the impact. Sometimes children meet and talk to the people and the communities who have faced these issues/instances to understand the same in a more empathetic and sensitive manner.  </p>
    <p>Singing the songs of people’s movement and discussing the ideas that those songs convey which can cultivate and nurture such thoughts is a part of our consistent activities. These songs resonate with the lives, situations and current realities of children. So the discussions around these songs also convey the reality of their own lives. Songs are also helpful in understanding difficulties and the challenges of life which are relevant. This also becomes a way to cultivate a concentrated thought.</p>
    <p>Through feature and documentary film screenings we discuss about diverse social, political and educational subjects with children. These films also help in cultivating perspectives among children. Screening films like ‘Bhaarat ek khoj’, ‘Samwidhaan’ and ‘agar me desh banati’ and discussing these with children has been a good experience. Such ways are a good medium to better understand diverse issues around the socio-political subjects.</p>
    <p>To connect the classroom learning with the lives of children who then collects the information from their community as well as other communities like Lohar, vegetable vendor, waste-collector, etc. through the interview and then share the experiences of the same in classroom and be able to analyze the same is part of our pedagogy which is very helpful. To establish a comprehensive thought process among the children, we also plan exposure visits very often. To understand the Gas tragedy of Bhopal, a visit to union carbide was planned and interviews with the people in nearby locality were conducted by the children with the situations of the current context in place. In this way, we conduct small study experiments with children around diverse topics.</p>
    </>
  )
}

export default BuildingPerspectives
